name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show Secret Status
        run: |
          echo "SERVER_IP length = ${#SERVER_IP}"
          echo "SERVER_USER length = ${#SERVER_USER}"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
