name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.SERVER_IP }}" ]; then
            echo "SERVER_IP is EMPTY"
          else
            echo "SERVER_IP exists"
          fi

          if [ -z "${{ secrets.SERVER_USER }}" ]; then
            echo "SERVER_USER is EMPTY"
          else
            echo "SERVER_USER exists"
          fi

          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "SERVER_SSH_KEY is EMPTY"
          else
            echo "SERVER_SSH_KEY exists"
          fi
